name: Maven Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version (e.g., 0.0.12)'
        required: true
        type: string
      nextVersion:
        description: 'Next development version (e.g., 0.0.13-SNAPSHOT)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Prepare Release
        run: |
          ./mvnw release:prepare \
            -DreleaseVersion=${{ inputs.releaseVersion }} \
            -DdevelopmentVersion=${{ inputs.nextVersion }} \
            -Dtag=v${{ inputs.releaseVersion }} \
            -DpushChanges=false \
            -B

      - name: Checkout Release Tag
        run: git checkout v${{ inputs.releaseVersion }}

      - name: Build Release Artifact
        run: ./mvnw clean package -DskipTests

      - name: Push Changes and Tags (Test Mode)
        run: |
          git push origin HEAD:test-release
          git push origin v${{ inputs.releaseVersion }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.releaseVersion }}
          name: Release v${{ inputs.releaseVersion }}
          draft: false
          prerelease: false
          files: target/mcp-contrast-${{ inputs.releaseVersion }}.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
